services:
  # Ros Backend
  ros_humble_pfms_container:
    image: ros-humble-pfms:latest
    volumes:
      - /:/root/ros2_ws/src
    environment:
      - DISPLAY=host.docker.internal:0.0
    working_dir: /root/ros2_ws
    # Yaml Block to enable GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

  # # Simulation Container
  # utsma_demo_sim:
  #   image: ros-humble-pfms:latest
  #   privileged: true
  #   networks:
  #     - host
  #   environment:
  #     - ROS_MASTER_URI=http://localhost:11311
  #     - DISPLAY=host.docker.internal:0.0
  #   command: bash -c "source /opt/ros/noetic/setup.bash && source /utsma_ws/devel/setup.bash && roslaunch utsma_gazebo simulation.launch"



  # # Path Planning Container
  # utsma_demo_path_planning:
  #   image: ros-humble-pfms:latest
  #   privileged: true
  #   networks:
  #     - host
  #   environment:
  #     - ROS_MASTER_URI=http://localhost:11311
  #     - DISPLAY=host.docker.internal:0.0
  #   command: bash -c "source /opt/ros/noetic/setup.bash && source /utsma_ws/devel/setup.bash && sleep 10 && rosrun d_triang utsma_path_planner"

  # # Code Viewer Container
  # utsma_demo_code_viewer:
  #   image: ros-humble-pfms:latest
  #   privileged: true
  #   networks:
  #     - host
  #   environment:
  #     - ROS_MASTER_URI=http://localhost:11311
  #     - DISPLAY=host.docker.internal:0.0
  #   command: bash -c "sleep infinity"